version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(swift):"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(python):"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(actions):"
    open-pull-requests-limit: 5
